#Here is the first config of the plugin
#config version 1.0-beta

self-gamemode-message: "§fGamemode has been changed to {mode}"
others-gamemode-message: "§fThe gamemode for {player} has been changed to {mode}"
self-fly-enabled-message: "§fYou have enabled flying mode"
self-fly-disabled-message: "§fYou have disabled flying mode"
others-fly-enabled-message: "§fYou have enabled flying mode for {player}"
others-fly-disabled-message: "§fYou have disabled flying mode for {player}"